CREATE TABLE public.snacks (
    id SERIAL PRIMARY KEY,
    category VARCHAR(30),
    name VARCHAR(30) NOT NULL,
    price NUMERIC(12,2) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);